from selenium import webdriver
from selenium.webdriver.support.ui import Select
import unittest
import time

class newSubmission(unittest.TestCase):
    def __init__(self, driver):
        super().__init__()
        self.driver = driver

    #creates a new submission with the following test inputs and files
    def new(self, user_type):
        time.sleep(1)
        self.driver.find_element_by_xpath('/html/body/header/div/nav/div/ul/li/a').click()
        self.driver.find_element_by_xpath('/html/body/header/div/nav/div/ul/li/ul/li[1]/a').click()
        self.driver.find_element_by_xpath('//*[@id="content"]/div[2]/div/div[2]/form/input[3]').click()
        select_collection = Select(self.driver.find_element_by_id('tcollection'))
        select_collection.select_by_value('56c641e2-583c-482b-a77c-d0c8d6722122')
        self.driver.find_element_by_xpath('//*[@id="content"]/div/form/div[3]/div/input[2]').click()
        time.sleep(.5)
        self.driver.find_element_by_id('dc_title').send_keys('Test Title')
        self.driver.find_element_by_id('dc_title_alternative_1').send_keys('Test Sub-title 1')
        # self.driver.find_element_by_xpath('//*[@id="edit_metadata"]/div[5]/div/div/button').click()
        # time.sleep(.5)
        # self.driver.find_element_by_id('dc_title_alternative_2').send_keys('Test Sub-title 2')
        select_agency = Select(self.driver.find_element_by_xpath('//*[@id="edit_metadata"]/div[7]/span/select'))
        select_agency.select_by_value('Records and Information Services, Department of (DORIS)')
        self.driver.find_element_by_id('dc_contributor_other_1').send_keys('Test Contributor 1')
        # self.driver.find_element_by_xpath('//*[@id="edit_metadata"]/div[9]/div/div/button/span').click()
        # time.sleep(.5)
        # self.driver.find_element_by_id('dc_contributor_other_2').send_keys('Test Contributor 2')
        select_category = Select(self.driver.find_element_by_xpath('//*[@id="subject-multiselect"]'))
        select_category.select_by_value('Accounting')
        select_category.select_by_value('Advertising')
        select_category.select_by_value('Alcohol')
        time.sleep(.25)
        self.driver.find_element_by_id('dc_description_abstract_id').send_keys('Test Description Enter Text Here est Description Enter Text Here est Description Enter Text Here est Description Enter Text Here est Description Enter Text Here')
        select_month = Select(self.driver.find_element_by_xpath('//*[@id="submission-month"]'))
        select_month.select_by_value('3')
        self.driver.find_element_by_xpath('//*[@id="submission-day"]').send_keys('23')
        self.driver.find_element_by_xpath('//*[@id="submission-year"]').send_keys('1909')
        select_type = Select(self.driver.find_element_by_xpath('//*[@id="edit_metadata"]/div[17]/span/select'))
        select_type.select_by_value('Calendars')
        time.sleep(.25)
        self.driver.find_element_by_xpath('//*[@id="fiscal-year"]').send_keys('1950')
        # self.driver.find_element_by_xpath('//*[@id="edit_metadata"]/div[21]/div/div/button').click()
        # time.sleep(.25)
        # self.driver.find_element_by_xpath('(//*[@id="fiscal-year"])[2]').send_keys('1951')
        self.driver.find_element_by_xpath('//*[@id="calendar-year"]').send_keys('1952')
        # self.driver.find_element_by_xpath('//*[@id="edit_metadata"]/div[23]/div/div/button').click()
        # time.sleep(.25)
        # self.driver.find_element_by_xpath('(//*[@id="calendar-year"])[2]').send_keys('1953')
        select_boro = Select(self.driver.find_element_by_xpath('//*[@id="edit_metadata"]/div[25]/span/select'))
        select_boro.select_by_value('bronx')
        select_boro.select_by_value('brooklyn')
        select_district = Select(self.driver.find_element_by_xpath('//*[@id="edit_metadata"]/div[27]/span/select'))
        select_district.select_by_value('District 1')
        select_district.select_by_value('District 3')
        select_district.select_by_value('District 7')
        select_board = Select(self.driver.find_element_by_xpath('//*[@id="edit_metadata"]/div[29]/span/select'))
        select_board.select_by_value('Bronx 5')
        select_board.select_by_value('Brooklyn 6')
        self.driver.find_element_by_xpath('//*[@id="dc_coverage_spatial-place_1"]').send_keys('Here')
        # self.driver.find_element_by_xpath('//*[@id="edit_metadata"]/div[31]/div/div/button/span').click()
        # self.driver.find_element_by_xpath('//*[@id="dc_coverage_spatial-place_2"]').send_keys('There')
        self.driver.find_element_by_xpath('//*[@id="submit-next"]').click()
        time.sleep(.25)
        self.driver.find_element_by_xpath('//*[@id="resumable-upload"]/div/a/input').send_keys('/Users/bzhuang/Documents/testFiles/testrecord1.docx')
        self.driver.find_element_by_xpath('//*[@id="tdescription"]').send_keys('Test Text')
        time.sleep(.5)
        self.driver.find_element_by_xpath('//*[@id="uploadForm"]/div[5]/input[3]').click()
        time.sleep(.5)
        self.driver.find_element_by_xpath('//*[@id="content"]/div/form/div[3]/input').click()
        self.driver.find_element_by_xpath('//*[@id="resumable-upload"]/div/a/input').send_keys('/Users/bzhuang/Documents/testFiles/TestFolder/testrecord2.docx')
        self.driver.find_element_by_xpath('//*[@id="tdescription"]').send_keys('Test Text')
        self.driver.find_element_by_xpath('//*[@id="uploadForm"]/div[5]/input[4]').click()
        time.sleep(.25)
        self.driver.find_element_by_xpath('//*[@id="content"]/div/form/div[4]/input[3]').click()
        time.sleep(.25)
        self.driver.find_element_by_xpath('//*[@id="content"]/div/form/input[3]').click()
